# "Скрижаль Хранилищ": главный раздел, который перечисляет, из каких
# "Небесных Кузниц" (репозиториев) мы будем призывать наших Стражей.
repos:

  # Первая запись в Скрижали: мы обращаемся к Кузнице `pre-commit/pre-commit-hooks`.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    # "Печать Времени": мы приказываем использовать Стражей именно версии `v4.6.0`,
    # чтобы ритуал был нерушим и воспроизводим.
    rev: v4.6.0
    # "Книга Призыва": мы перечисляем, каких именно духов-стражей из этой Кузницы
    # мы призываем на службу.
    hooks:
      # "Страж-Чистильщик Хвостов": этот дух автоматически удаляет
      # призрачные, невидимые пробелы в конце строк.
      - id: trailing-whitespace

      # "Страж Последней Руны": этот дух гарантирует, что каждый пергамент
      # заканчивается одной-единственной пустой строкой, как того требует древний Канон.
      - id: end-of-file-fixer

      # "Страж Гармонии YAML": этот дух проверяет, что все наши чертежи Стражей
      # (`*.yml`) написаны без синтаксических ошибок.
      - id: check-yaml

      # "Страж-Привратник": этот дух бдительно следит, чтобы ты случайно
      # не попытался запечатать в Летопись `Git` слишком тяжелый артефакт
      # (например, файл > 5 МБ), который должен находиться под опекой `DVC`.
      - id: check-added-large-files

  # Вторая запись в Скрижали: мы обращаемся к Кузнице `psf/black`.
  - repo: https://github.com/psf/black
    # "Печать Времени": мы призываем духа `black` именно версии `24.4.2`.
    rev: 24.4.2
    # "Книга Призыва":
    hooks:
      # "Каллиграф-Тиран": мы призываем самого духа `black`. При каждом `git commit`,
      # он автоматически перекует твои `.py` файлы в свой нерушимый, единый стиль.
      - id: black
        # "Особый Указ": мы передаем Каллиграфу дополнительный приказ,
        # чтобы он следовал нашему "Закону 88 Рун".
        args: [--line-length=88]

  # Третья запись в Скрижали: мы обращаемся к Кузнице `pycqa/flake8`.
  - repo: https://github.com/pycqa/flake8
    # "Печать Времени": мы призываем Инквизитора `flake8` версии `7.1.0`.
    rev: 7.1.0
    # "Книга Призыва":
    hooks:
      # "Инквизитор": мы призываем духа `flake8`. После того, как "Каллиграф"
      # завершит свою работу, "Инквизитор" проведет финальный аудит и убедится,
      # что не осталось никаких грехов стиля или логики.
      - id: flake8