# "Скрижаль Хранилищ": главный раздел, который перечисляет, из каких
# "Небесных Кузниц" (репозиториев) мы будем призывать наших Стражей.
repos:
  # Первая запись в Скрижали: мы обращаемся к Кузнице `pre-commit/pre-commit-hooks`.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    # "Печать Времени": мы приказываем использовать Стражей именно версии `v4.6.0`,
    # чтобы ритуал был нерушим и воспроизводим.
    rev: v6.0.0
    # "Книга Призыва": мы перечисляем, каких именно духов-стражей из этой Кузницы
    # мы призываем на службу.
    hooks:
      # "Страж-Чистильщик Хвостов": этот дух удаляет невидимые пробелы в конце строк.
      # Мы приказали ему не трогать пергаменты Markdown (`.md`), чтобы избежать
      # священной войны с "Хранителем Эстетики" (`prettier`), который правит на этих землях.
      - id: trailing-whitespace
        exclude: \.md$

      # "Страж Последней Руны": этот дух гарантирует, что каждый пергамент
      # заканчивается одной-единственной пустой строкой, как того требует древний Канон.
      - id: end-of-file-fixer

      # "Страж Гармонии YAML": этот дух проверяет, что все наши чертежи Стражей
      # (`*.yml`) написаны без синтаксических ошибок.
      - id: check-yaml

      # "Страж-Привратник": этот дух бдительно следит, чтобы ты случайно
      # не попытался запечатать в Летопись `Git` слишком тяжелый артефакт
      # (например, файл > 5 МБ), который должен находиться под опекой `DVC`.
      - id: check-added-large-files

  # Вторая запись в Скрижали: мы обращаемся к Кузнице `psf/black`.
  - repo: https://github.com/psf/black
    # "Печать Времени": мы призываем духа `black` именно версии `24.4.2`.
    rev: 25.9.0
    # "Книга Призыва":
    hooks:
      # "Каллиграф-Тиран": мы призываем самого духа `black`. При каждом `git commit`,
      # он автоматически перекует твои `.py` файлы в свой нерушимый, единый стиль.
      - id: black
        # "Особый Указ": мы передаем Каллиграфу дополнительный приказ,
        # чтобы он следовал нашему "Закону 88 Рун".
        args: [--line-length=88]

  # Третья запись в Скрижали: мы обращаемся к Кузнице `pycqa/flake8`.
  - repo: https://github.com/pycqa/flake8
    # "Печать Времени": мы призываем Инквизитора `flake8` версии `7.1.0`.
    rev: 7.3.0
    # "Книга Призыва":
    hooks:
      # "Инквизитор": мы призываем духа `flake8`. После того, как "Каллиграф"
      # завершит свою работу, "Инквизитор" проведет финальный аудит и убедится,
      # что не осталось никаких грехов стиля или логики.
      - id: flake8
        args:
          - "--per-file-ignores=Part_4_Engineering/Scroll_26/Quest_1/spell_with_flaw.py:F401"

  # Четвертая запись в Скрижали: мы обращаемся к Кузнице `PyCQA/docformatter`.
  - repo: https://github.com/PyCQA/docformatter
    # "Печать Времени": мы призываем Хранителя Докстрингов `docformatter` версии `v1.7.5`.
    rev: v1.7.7
    # "Книга Призыва":
    hooks:
      # "Хранитель Докстрингов": мы призываем духа `docformatter`.
      - id: docformatter
        # "Особый Указ": мы передаем ему три приказа:
        # --in-place: исправлять файлы напрямую (а не просто сообщать об ошибках).
        # --wrap-summaries=88: переносить однострочные докстринги по границе 88 символов.
        # --wrap-descriptions=88: переносить многострочные докстринги по границе 88 символов.
        args: [--in-place, --wrap-summaries=88, --wrap-descriptions=88]

  # Пятая запись в Скрижали: мы обращаемся к Кузнице `pre-commit/mirrors-prettier`.
  - repo: https://github.com/pre-commit/mirrors-prettier
    # "Печать Времени": мы призываем Хранителя `prettier` версии `v4.0.0`.
    rev: v4.0.0-alpha.8
    # "Книга Призыва":
    hooks:
      # "Хранитель Эстетики": мы призываем духа `prettier`. Он будет следить
      # за красотой и стилем наших пергаментов (`.md`) и чертежей (`.yml`),
      # приводя их в соответствие с Уставом `.prettierrc.json`.
      - id: prettier
