# Мы начинаем главу 'Великий Указ' (global), где устанавливаем общие, незыблемые законы для нашего 'Стража-Летописца'.
global:
  # Мы приказываем 'Стражу' заглядывать в мир и опрашивать своих подопечных (собирать метрики) каждые 15 секунд.
  scrape_interval: 15s

# Здесь начинается 'Свиток Обязанностей' (scrape_configs), где мы перечисляем, за кем именно должен следить наш 'Страж'.
scrape_configs:
  # Мы начинаем первую запись в 'Свитке' и даем этому заданию ('job_name') имя 'fastapi-app',
  # чтобы потом легко понимать, откуда пришли летописи (метрики).
  - job_name: 'fastapi-app'
    # Мы объявляем, что будем использовать 'Пакт Прямого Наблюдения' (static_configs), указывая точные координаты цели вручную.
    static_configs:
      # Это — финальный, самый точный приказ. Мы говорим 'Стражу':
      # "Направь свой взор на существо по имени `app` (наш 'Говорящий Амулет')
      # и загляни в его 'Окно Наблюдения' (`/metrics`) на порту `8000`".
      # Магия 'Магической Сети' (Docker-Compose) сама укажет 'Стражу' путь к 'app'.
      - targets: ['app:8000']
      