# Мы указываем версию "древнего языка Docker-Compose" (3.8), на котором написан этот чертеж.
version: "3.8"

# Здесь начинается "Перечень Существ" — глава, описывающая каждого Голема, которого мы призовем.
services:
  # Имя первого, главного Голема в нашей гильдии — наш "Говорящий Амулет".
  app:
    # Мы описываем "Ритуал Сотворения" этого Голема.
    build:
      # Мы указываем "Место Силы" (`context`) — путь к пергаментам (Dockerfile) для его сотворения.
      # `.` — означает "ищи чертежи в той же папке, где лежит этот Великий Чертеж".
      context: .
    # Мы описываем "Окна в Мир" — какие порталы Голема будут видны нам.
    ports:
      # "Руна Связи": мы соединяем порт 8000 нашего мира (слева) с портом 8000 внутри Голема (справа).
      - "8000:8000"
    # Мы указываем, к каким "Магическим Сетям" будет подключен этот Голем.
    networks:
      # Он будет состоять в нашей тайной "Сети Наблюдения".
      - monitoring-net
    # Мы вкладываем в разум Голема "Секретные Руны Окружения".
    environment:
      # Мы даруем ему знание о том, на каком порту ему следует открыть свой внутренний портал.
      - PORT=8000

  # Имя второго Голема — наш "Страж-Летописец" (Prometheus).
  prometheus:
    # Мы не создаем его сами, а призываем готового из "Великой Библиотеки" (Docker Hub).
    image: prom/prometheus:latest
    # Мы даруем ему "Истинное Имя", чтобы легко находить его среди других духов.
    container_name: prometheus_guardian
    # Мы создаем "Магические Узы" (volumes), связывающие наш мир с миром Голема.
    volumes:
      # Мы связываем наш свиток с правилами (`prometheus.yml`) со священным местом для правил внутри Голема.
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    # Мы открываем "Окно" в мир на порту 9090.
    ports:
      # "Руна Связи" для "Стража".
      - "9090:9090"
    # Мы накладываем "Пакт Зависимости":
    depends_on:
      # "Страж" пробудится только ПОСЛЕ того, как наш главный "Амулет" (`app`) будет готов.
      - app
    # Мы также подключаем его к нашей тайной сети.
    networks:
      # Он будет состоять в "Сети Наблюдения".
      - monitoring-net

  # Имя третьего Голема — наш "Провидец с Хрустальным Зеркалом" (Grafana).
  grafana:
    # Мы также призываем его из "Великой Библиотеки".
    image: grafana/grafana:latest
    # Мы даруем ему его "Истинное Имя".
    container_name: grafana_seer
    # Мы открываем "Окно" в мир на порту 3000.
    ports:
      # "Руна Связи" для "Провидца".
      - "3000:3000"
    # Мы накладываем второй "Пакт Зависимости":
    depends_on:
      # "Провидец" пробудится только ПОСЛЕ того, как "Страж" (`prometheus`) займет свой пост.
      - prometheus
    # И он тоже будет частью нашей сети.
    networks:
      # Он будет состоять в "Сети Наблюдения".
      - monitoring-net

# Здесь начинается "Глава о Магических Сетях", где мы описываем каналы связи.
networks:
  # Мы даем имя нашей тайной сети.
  monitoring-net:
    # Мы указываем, что это стандартная 'мостовая' сеть, создающая изолированный эфирный канал для наших Големов.
    driver: bridge
