# --- Гримуар "Пробуждение Цитадели" (docker-compose.yml) ---

# Декларация версии гримуара. Руна '3.8' сообщает Великому Духу Docker, по каким законам магии читать этот свиток.
version: '3.8'

# Глава "Призыв Духов": здесь мы описываем всех магических существ, которых призовем в наш мир.
services:

  # Истинное имя первого духа: наш Артефакт, 'app'.
  app:
    # Ритуал сотворения: вместо призыва готового духа, мы создаем его сами по чертежам из нашего 'Dockerfile'.
    build:
      # Та самая 'Исправленная Руна' '.', указывающая на нашу текущую мастерскую. Все нужные для ритуала компоненты находятся здесь.
      context: .
    # Открытие портала: мы соединяем портал '8000' в нашем мире с порталом '8000' в измерении духа 'app'.
    ports:
      - "8000:8000"
    # Подключение к магическому каналу: мы позволяем этому духу общаться с другими по каналу 'monitoring-net'.
    networks:
      - monitoring-net
    # Тайное знание: мы шепчем духу при рождении, какие переменные он должен знать, чтобы функционировать.
    environment:
      # Нашептываем ему: "Ты будешь слушать мир через портал номер 8000".
      - PORT=8000

  # Истинное имя второго духа: наш Страж Времени, 'prometheus'.
  prometheus:
    # Призыв из Великой Библиотеки: мы призываем могущественного, готового духа 'prom/prometheus' последней версии.
    image: prom/prometheus:latest
    # Даем ему ритуальное имя в нашем мире: 'prometheus_guardian', чтобы мы могли его легко опознать.
    container_name: prometheus_guardian
    # Магическая связь: мы создаем нерушимую связь между файлами в нашем мире и миром духа.
    volumes:
      # Мы передаем ему наш свиток с правилами 'prometheus.yml', чтобы он знал, за кем и как следить.
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    # Открытие портала: мы открываем портал '9090', чтобы заглядывать в его летописи.
    ports:
      - "9090:9090"
    # Пакт о последовательности: этот дух пробудится только ПОСЛЕ того, как дух 'app' будет полностью готов.
    depends_on:
      - app
    # Подключение к магическому каналу: Страж должен быть в том же канале, чтобы слышать нашего 'app'.
    networks:
      - monitoring-net

  # Истинное имя третьего духа: наш Провидец Зеркала, 'grafana'.
  grafana:
    # Призыв из Великой Библиотеки: мы призываем еще одного готового духа 'grafana/grafana' последней версии.
    image: grafana/grafana:latest
    # Даем ему ритуальное имя: 'grafana_seer', Провидец.
    container_name: grafana_seer
    # Открытие портала: мы открываем портал '3000', чтобы заглядывать в его магическое зеркало.
    ports:
      - "3000:3000"
    # Пакт о последовательности: Провидец пробудится только ПОСЛЕ того, как Страж 'prometheus' будет готов передавать ему видения.
    depends_on:
      - prometheus
    # Подключение к магическому каналу: Провидец должен быть в том же канале, чтобы говорить со Стражем.
    networks:
      - monitoring-net

# Глава "Магические Каналы": здесь мы описываем сами каналы связи для наших духов.
networks:
  # Имя нашего единственного, но надежного канала связи.
  monitoring-net:
    # Тип магии, используемый для создания канала. 'bridge' — это стандартная магия для общения духов в пределах одной цитадели.
    driver: bridge