# Версия синтаксиса "Гримуара Оркестровки".
version: '3.8'

# Главный раздел, где мы описываем всех наших "духов" (сервисы/контейнеры).
services:
  # Имя нашего первого духа - "Говорящий Амулет".
  api:
    # 'build: .' - приказ: "Собери его 'тело' (образ) по чертежу 'Dockerfile' из текущей папки".
    build: .
    # 'ports' - "Открой портал из внешнего мира в его карманное измерение".
    # "8000:8000" - свяжи порт 8000 на твоей машине с портом 8000 внутри контейнера.
    ports:
      - "8000:8000"
    # 'environment' - "Начертай эти 'секретные руны' внутри его карманного измерения".
    environment:
      # Мы явно указываем, что Хранитель Памяти живет по адресу 'redis'.
      - REDIS_HOST=redis
    # 'depends_on' - "Этот дух зависит от...".
    depends_on:
      # "...духа по имени 'redis'". Docker-Compose гарантирует, что 'redis' запустится ПЕРЕД 'api'.
      - redis

  # Имя нашего второго духа - "Хранитель Памяти".
  redis:
    # 'image: "redis:alpine"' - приказ: "Не строй его, а призови готовый образ из Великой Библиотеки Docker Hub".
    image: "redis:alpine"