# Имя нашего ритуала, которое будет видно в интерфейсе GitHub.
name: Ритуал Проверки Чистоты

# "Триггер": Заклинание, которое пробуждает Стража.
# 'on: [push]' - означает "Пробуждайся при каждом 'git push' в любую ветку".
on: [push]

# "Задания": Список задач, которые должен выполнить Страж.
jobs:
  # Мы даем нашей задаче уникальное имя 'check-purity-of-runes'.
  check-purity-of-runes:
    # "Алтарь": Указываем, в каком "мире" будет работать Страж.
    # 'ubuntu-latest' - это чистая, свежая виртуальная машина с Ubuntu.
    runs-on: ubuntu-latest

    # "Шаги Ритуала": Последовательность действий, которые выполняет Страж.
    steps:
      # Шаг 1: "Призыв Летописи".
      # 'uses: actions/checkout@v4' - это стандартное заклинание, которое
      # копирует код из твоего репозитория в рабочую зону Стража.
      - name: 1. Призыв Летописи (Checkout Code)
        uses: actions/checkout@v4

      # Шаг 2: "Создание Магического Круга Python".
      # Это заклинание подготавливает окружение Python нужной нам версии.
      - name: 2. Создание Магического Круга (Set up Python)
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Шаг 3: "Призыв Ока Чистоты".
      # 'run:' - означает "выполни эту команду в терминале".
      - name: 3. Призыв Ока Чистоты (Install flake8)
        run: pip install flake8

      # Шаг 4: "Великая Проверка".
      # Страж запускает 'flake8' для проверки ВСЕХ файлов в репозитории.
      # Этот шаг должен ПРОВАЛИТЬСЯ из-за нашей приманки.
      - name: 4. Великая Проверка (Run flake8)
        run: flake8 .