name: MLOps Capstone Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'quest_32_1/**'

jobs:
  build-test-deploy:
    name: Build, Test, and Deploy the Capstone Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: pip install -r ./quest_32_1/requirements.txt
      
      - name: Authenticate to Google Cloud
        id: auth # <-- Даем ID шагу
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Build and Push Docker Image
        run: |
          # <-- Используем ID проекта из ВЫХОДА шага 'auth'
          docker build -t europe-north1-docker.pkg.dev/${{ steps.auth.outputs.project_id }}/codex-artifacts/amulet:${{ github.sha }} ./quest_32_1
          docker push europe-north1-docker.pkg.dev/${{ steps.auth.outputs.project_id }}/codex-artifacts/amulet:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          # <-- И здесь тоже
          image: europe-north1-docker.pkg.dev/${{ steps.auth.outputs.project_id }}/codex-artifacts/amulet:${{ github.sha }}
          service: 'codex-amulet'
          region: 'europe-north1'