name: Build and Push Docker Image via WIF

on:
  push:
    branches:
      - 'main'
    paths:
      - 'quest_32_1/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: europe-north1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./quest_32_1
          push: true
          tags: europe-north1-docker.pkg.dev/${{ steps.auth.outputs.project_id }}/codex-artifacts/amulet:${{ github.sha }}

      # ЗАМЕТКА АРХИТЕКТОРА: Этот шаг пока закомментирован.
      # Мы активируем его, когда убедимся, что сборка и отправка работают идеально.
      # - name: Deploy to Cloud Run
      #   uses: google-github-actions/deploy-cloudrun@v2
      #   with:
      #     service: 'codex-amulet'
      #     region: 'europe-north1'
      #     image: europe-north1-docker.pkg.dev/${{ steps.auth.outputs.project_id }}/codex-artifacts/amulet:${{ github.sha }}