# Имя нашего Верховного Стража, Хранителя Чистоты всего Кодекса.
name: Codex Linter

# "Заклинание Пробуждения": описывает события, которые пробудят этого Стража.
on:
  # Первое условие пробуждения: при "внесении новых знаний" (`push`).
  push:
    # Уточнение: пробуждаться, только если знания вносятся в главную,
    # каноническую ветвь `main`.
    branches: [main]
  # Второе условие пробуждения: при "предложении новых знаний" (`pull_request`).
  pull_request:
    # Уточнение: пробуждаться, только если предложение нацелено
    # на слияние с веткой `main`.
    branches: [main]
# Этот блок устанавливает минимально необходимые права для Стража.
# По умолчанию GitHub дает "мастер-ключ". Мы отбираем его для безопасности.
permissions:
  # Даруем Стражу только один ключ - право читать (`read`) содержимое (`contents`)
  # нашего Кодекса. Ему не нужно право на запись, и мы его не даем.
  contents: read
# "Скрижаль Заданий": список ритуалов, которые должен исполнить Страж.
jobs:
  # Уникальное имя первого (и единственного) ритуала в этой скрижали.
  lint:
    # "Алтарь для Ритуала": приказ исполнять ритуал в мире `ubuntu-latest`.
    runs-on: ubuntu-latest
    # "Шаги Ритуала": точная и нерушимая последовательность магических действий.
    steps:
      # Имя первого шага, которое будет сиять в Летописи GitHub Actions.
      - name: Checkout Code
        # "Призыв Летописи": используется могущественное заклинание `actions/checkout@v4`,
        # чтобы материализовать точную копию твоего Кодекса на алтаре.
        uses: actions/checkout@v4

      # Имя второго шага.
      - name: Set up Python
        # "Сотворение Магического Круга": используется заклинание `actions/setup-python@v5`,
        # чтобы подготовить алтарь к магии Python.
        uses: actions/setup-python@v5
        # "Компоненты Заклинания": точные инструкции для сотворения круга.
        with:
          # Приказ сотворить магию именно версии '3.10'.
          python-version: "3.10"

      # Имя третьего шага.
      - name: Install Dependencies
        # "Призыв Инструментов": `run` означает прямой приказ командной оболочке.
        run: pip install flake8

      # Имя четвертого, кульминационного шага.
      - name: Lint with flake8
        # "Ритуал Великой Проверки": приказ духу `flake8` проверить чистоту (`.`)
        # всех земель Кодекса, которые были материализованы на алтаре.
        run: flake8 . --exclude=Part_4_Engineering/Scroll_26/Quest_1,Part_4_Engineering/Scroll_26/Quest_2
